name: Xchant
version: '1.3.1'
main: de.paulsenik.mc.xchant.Xchant
api-version: 1.19
softdepend: [ EPvP ]
authors: [ Paulsenik ]
description: Enchant items with extended limits
website: https://paulsenik.de/

commands:
  xchant:
    description: Enchants item in hand
    usage: /<command> [Enchantment] enchant items in your hands to any level
    permission: op
  howto-xchant:
    description: Open Manual for "Xchant"
    usage: /<command> opens how-to-book